### ISSUE TITLE
sourceclear-invoker cannot correctly scan 3scale apicast-operator repo

### ISSUE THREAD

**Issue by gsaslis** [project-ncl/sourceclear-invoker#100]
I try to scan the repository and it seems like sourceclear-invoker is hitting some issue parsing the output: 

```bash
$ mvn -Pjenkins clean test -DargLine='-Xmx4G -Dsourceclear="--product=3scale/apicast-operator --product-version=2.11.0 scm --url=https://github.com/3scale/apicast-operator.git --ref=master "'
[INFO] Scanning for projects...
[INFO]
[INFO] -------------------< com.redhat.engineering:srcclr >--------------------
[INFO] Building SourceClear JUnit Wrapper 1.6-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:3.0.0:clean (default-clean) @ srcclr ---
[INFO] Deleting /Users/yorgos/dev/redhat/3scale/sourceclear-invoker/target
[INFO]
[INFO] --- buildnumber-maven-plugin:1.4:create (buildnumber) @ srcclr ---
[INFO] ShortRevision tag detected. The value is '8'.
[INFO] Executing: /bin/sh -c cd '/Users/yorgos/dev/redhat/3scale/sourceclear-invoker' && 'git' 'rev-parse' '--verify' '--short=8' 'HEAD'
[INFO] Working directory: /Users/yorgos/dev/redhat/3scale/sourceclear-invoker
[INFO] Storing buildNumber: e055da2f at timestamp: 01 February 2021
[INFO] Storing buildScmBranch: master
[INFO]
[INFO] --- maven-enforcer-plugin:3.0.0-M1:enforce (enforce-versions) @ srcclr ---
[INFO] Skipping Rule Enforcement.
[INFO]
[INFO] --- maven-enforcer-plugin:3.0.0-M1:enforce (avoid-trip-hazards) @ srcclr ---
[INFO] Skipping Rule Enforcement.
[INFO]
[INFO] --- maven-enforcer-plugin:3.0.0-M1:enforce (enforce-best-practices) @ srcclr ---
[INFO] Skipping Rule Enforcement.
[INFO]
[INFO] --- maven-resources-plugin:3.0.2:resources (default-resources) @ srcclr ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.7.0:compile (default-compile) @ srcclr ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 43 source files to /Users/yorgos/dev/redhat/3scale/sourceclear-invoker/target/classes
[INFO] /Users/yorgos/dev/redhat/3scale/sourceclear-invoker/src/main/java/com/redhat/engineering/srcclr/SrcClrWrapper.java: /Users/yorgos/dev/redhat/3scale/sourceclear-invoker/src/main/java/com/redhat/engineering/srcclr/SrcClrWrapper.java uses or overrides a deprecated API.
[INFO] /Users/yorgos/dev/redhat/3scale/sourceclear-invoker/src/main/java/com/redhat/engineering/srcclr/SrcClrWrapper.java: Recompile with -Xlint:deprecation for details.
[INFO]
[INFO] --- maven-enforcer-plugin:3.0.0-M1:enforce (enforce-commonjava-standards) @ srcclr ---
[INFO] Skipping Rule Enforcement.
[INFO]
[INFO] --- maven-resources-plugin:3.0.2:testResources (default-testResources) @ srcclr ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 3 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.7.0:testCompile (default-testCompile) @ srcclr ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 12 source files to /Users/yorgos/dev/redhat/3scale/sourceclear-invoker/target/test-classes
[INFO]
[INFO] --- maven-surefire-plugin:3.0.0-M3:test (default-test) @ srcclr ---
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.redhat.engineering.srcclr.SourceClearTest
[INFO] Retrieved argument [--product, 3scale/apicast-operator, --product-version, 2.11.0, scm, --url=https://github.com/3scale/apicast-operator.git, --ref=master]
[INFO] Invoking in environment {GIT_BRANCH=null, GIT_URL=null, GOPATH=/var/folders/0h/28qktgvj01j9hp61hck2p7sc0000gn/T/sourceclear-gopath-4886510764422553483} command [/usr/local/Cellar/srcclr/3.7.9/libexec/jre/bin/java, -jar, /usr/local/Cellar/srcclr/3.7.9/libexec/srcclr-3.7.9.jar, scan, --json, /var/folders/0h/28qktgvj01j9hp61hck2p7sc0000gn/T/sourceclear-json-8946556462077758082/6d97b96e-0e5b-4e69-9fb9-4162475961bc, --url, https://github.com/3scale/apicast-operator.git, --ref, master] ....
[INFO] Found vulnerability 'Directory Traversal' with CVE ID 2014-9358 in library github.com/docker/docker::v0.7.3
[INFO] Found vulnerability 'Directory Traversal' with CVE ID 2014-9356 in library github.com/docker/docker::v0.7.3
[INFO] Found vulnerability 'DNS Rebinding' with CVE ID 2018-1099 in library github.com/coreos/etcd::v3.3.10
[INFO] Found vulnerability 'Cross-site Request Forgery (CSRF)' with CVE ID 2018-1098 in library github.com/coreos/etcd::v3.3.10
[INFO] Found vulnerability 'Denial Of Service (DoS)' with CVE ID 2020-27813 in library github.com/gorilla/websocket::v1.4.0
[INFO] Found vulnerability 'Authorization Bypass' with CVE ID 2020-26160 in library github.com/dgrijalva/jwt-go::v3.2.0
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 61.659 s <<< FAILURE! - in com.redhat.engineering.srcclr.SourceClearTest
[ERROR] runSourceClear(com.redhat.engineering.srcclr.SourceClearTest)  Time elapsed: 61.621 s  <<< ERROR!
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at com.redhat.engineering.srcclr.SourceClearTest.runSourceClear(SourceClearTest.java:35)

[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   SourceClearTest.runSourceClear:35->SCBase.exeSC:44 » IndexOutOfBounds Index: 0...
[INFO]
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:06 min
[INFO] Finished at: 2021-02-01T22:45:11+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M3:test (default-test) on project srcclr: There are test failures.
[ERROR]
[ERROR] Please refer to /Users/yorgos/dev/redhat/3scale/sourceclear-invoker/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by rnc** [comment]
Looks like a bug - maybe they have changed their output. Trace with more debugging is
```
[ERROR] Exception running sourceclear
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:657)
        at java.util.ArrayList.get(ArrayList.java:433)
        at com.redhat.engineering.srcclr.processor.JSONResult.locateLibrary(JSONResult.java:38)
        at com.redhat.engineering.srcclr.processor.CVEProcessor.process(CVEProcessor.java:52)
        at com.redhat.engineering.srcclr.SCM.call(SCM.java:124)
        at com.redhat.engineering.srcclr.SCM.call(SCM.java:40)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunAll.recursivelyExecuteUserObject(CommandLine.java:2422)
        at picocli.CommandLine$RunAll.recursivelyExecuteUserObject(CommandLine.java:2424)
        at picocli.CommandLine$RunAll.handle(CommandLine.java:2419)
        at picocli.CommandLine$RunAll.handle(CommandLine.java:2383)
        at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:2172)
        at picocli.CommandLine.parseWithHandlers(CommandLine.java:2550)
        at com.redhat.engineering.srcclr.SrcClrWrapper.invokeWrapper(SrcClrWrapper.java:133)
        at com.redhat.engineering.srcclr.SCBase.exeSC(SCBase.java:44)
        at com.redhat.engineering.srcclr.SourceClearTest.runSourceClear(SourceClearTest.java:38)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
        at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
        at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 208.617 s - in com.redhat.engineering.srcclr.SourceClearTest
```

**Comment by rnc** [comment]
Reference for anyone coming to this - we should change SourceClearTest so it logs errors like this e.g. 
```
  index 66c5c20..a25c148 100644
  --- a/src/test/java/com/redhat/engineering/srcclr/SourceClearTest.java
  +++ b/src/test/java/com/redhat/engineering/srcclr/SourceClearTest.java
  @@ -32,7 +32,10 @@ public class SourceClearTest extends SCBase
       @Test
       public void runSourceClear() throws Exception
       {
  -        SourceClearResult result = exeSC();
  +        SourceClearResult result;
  +        try
  +        {
  +            result = exeSC();
   
               if ( !result.isPass() )
               {
  @@ -40,4 +43,10 @@ public class SourceClearTest extends SCBase
                   Assert.fail( result.getMessage() );
               }
           }
  +        catch ( Exception e )
  +        {
  +            logger.error( "Exception running sourceclear", e );
  +            throw e;
  +        }
  +    }
   }
```

**Comment by rnc** [comment]
@gsaslis Hi. I've rebased my local repo on top of the work done for #99 and rerun your command using srcclr-3.7.11-1.noarch
``
`mvn -Pjenkins clean test -DargLine='-Xmx4G -Dsourceclear="--product=3scale/apicast-operator --product-version=2.11.0 scm --url=https://github.com/3scale/apicast-operator.git --ref=master "'                   
```

and I get

```
[INFO] Running com.redhat.engineering.srcclr.SourceClearTest
[INFO] Retrieved argument --product 3scale/apicast-operator --product-version 2.11.0 scm --url=https://github.com/3scale/apicast-operator.git --ref=master
[INFO] Invoking in environment {GIT_BRANCH=null, GIT_URL=null, GOPATH=/tmp/sourceclear-gopath-2137316466760560939} with command {/opt/srcclr-3.7.11/jre/bin/java -Xmx3817865216 -jar /opt/srcclr-3.7.11/srcclr-3.7.11.jar -Dsun.jnu.encoding=UTF-8 -Dfile.encoding=UTF-8  -Dhttps.protocols=TLSv1.2,TLSv1.1,TLSv1 scan --json /tmp/sourceclear-json-7344602079444056972/7e322e95-f4fa-49cd-a7b4-d338b6e7b6a9 --url https://github.com/3scale/apicast-operator.git --ref master}
```

This appears to complete successfully for me now so perhaps something changed between 3.7.9 and 3.7.11 ? Unless you have any objection I'm therefore going to close this.

**Comment by gsaslis** [comment]
@rnc thanks for this. 

I can confirm upgrading to `srcclr` version `3.7.11` has resolved the issue.
