### ISSUE TITLE
Help output throws "InternalException: Command line parse exception"

### ISSUE THREAD

**Issue by tombentley** [project-ncl/sourceclear-invoker#71]
Running the tool with no options or `--help` prints some help info followed by a stacktrace.

```
$ java -jar target/srcclr-1.4-SNAPSHOT-jar-with-dependencies.jar
Missing required options [--product=<product>, --product-version=<version>]
Usage: SrcClrWrapper [-dehV] [--trace] [--email-server=<emailServer>]
                     -p=<product> [--package=<packageName>]
                     [--processor=<processor>] [-t=<threshold>] -v=<version>
                     [--email-address=<emailAddresses>[,
                     <emailAddresses>...]]... [COMMAND]
Wrap SourceClear and invoke it.
  -d, --debug               Enable debug.
  -e, --exception           Throw exception on vulnerabilities found.
      --email-address=<emailAddresses>[,<emailAddresses>...]
                            Comma separated list of email address to notify.
                              Domain portion will be used as FROM address
      --email-server=<emailServer>
                            SMTP Server to use to send notification email
  -h, --help                Show this help message and exit.
  -p, --product=<product>   Product Name (in same format as CPE Product Name)
      --package=<packageName>
                            Package name. It's optional but required for RHOAR,
                              e.g. (vertx|swarm|springboot).
      --processor=<processor>
                            Processor (cve|cvss) to use to analyse SourceClear
                              results. Default is cve
  -t, --threshold=<threshold>
                            Threshold on which exception is thrown. Only used
                              with CVSS Processor
      --trace               Enable trace. Will DISABLE JSON OUTPUT
  -v, --product-version=<version>
                            Version of the product
  -V, --version             Print version information and exit.
Commands:
  scm     Scan a SCM URL (unmatched args are passed directly to SourceClear)
  binary  Scan a remote binary (unmatched args are passed directly to
            SourceClear)
Exception in thread "main" com.redhat.engineering.srcclr.utils.InternalException: Command line parse exception
	at com.redhat.engineering.srcclr.SrcClrWrapper.invokeWrapper(SrcClrWrapper.java:127)
	at com.redhat.engineering.srcclr.SrcClrWrapper.main(SrcClrWrapper.java:111)
```

**Comment by rnc** [comment]
Fixed by #72
