### ISSUE TITLE
`mvn package` fails with `"glide" is not installed or not found on PATH`

### ISSUE THREAD

**Issue by gsaslis** [project-ncl/sourceclear-invoker#81]
I'm on OSX (10.14) and after I've installed the `srcclr` command-line tool, and activated it with `srcclr activate` I now get a bunch of errors when running `mvn package`, including get a different error: 

```
2019-11-20/15:36:12.742 com.sourceclear.engine.component.ComponentEngineBuilder	DEBUG	Invalid collector name is specified: "SOFILE"
2019-11-20/15:36:12.742 com.sourceclear.engine.component.ComponentEngineBuilder	DEBUG	collectorsToRun: []
2019-11-20/15:36:12.743 com.sourceclear.engine.component.ComponentEngineBuilder	DEBUG	collectorsToSkip: []
2019-11-20/15:36:12.864 com.sourceclear.agent.commands.ScanCommand	INFO	"glide" is not installed or not found on PATH
2019-11-20/15:36:12.864 com.sourceclear.agent.commands.ScanCommand	INFO	Error while configuring engine
2019-11-20/15:36:12.932 com.sourceclear.agent.EntryPointImpl	DEBUG	Exiting with 1

com.sourceclear.agent.FatalException: SourceClear is unable to continue with scanning the project because at least one\nof the build systems we found for your project is not ready for build.\nWe suggest you scan the project again after reviewing and correcting the errors.
	at com.sourceclear.agent.commands.ScanCommand.handleScanErrors(ScanCommand.java:972)
	at com.sourceclear.agent.commands.ScanCommand.executeRepoScan(ScanCommand.java:749)
	at com.sourceclear.agent.commands.ScanCommand.execute(ScanCommand.java:469)
	at com.sourceclear.agent.EntryPointImpl.runVerb(EntryPointImpl.java:371)
	at com.sourceclear.agent.EntryPointImpl.dispatchVerbOptions(EntryPointImpl.java:320)
	at com.sourceclear.agent.EntryPointImpl.apply(EntryPointImpl.java:156)
	at com.sourceclear.agent.Main.start(Main.java:96)
	at com.sourceclear.agent.Main.main(Main.java:101)
Caused by:
	com.sourceclear.engine.component.CollectionException: SourceClear is unable to continue with scanning the project because at least one\nof the build systems we found for your project is not ready for build.\nWe suggest you scan the project again after reviewing and correcting the errors.
		at com.sourceclear.agent.commands.ScanCommand.handleScanErrors(ScanCommand.java:972)
		at com.sourceclear.agent.commands.ScanCommand.executeRepoScan(ScanCommand.java:749)
		at com.sourceclear.agent.commands.ScanCommand.execute(ScanCommand.java:469)
		at com.sourceclear.agent.EntryPointImpl.runVerb(EntryPointImpl.java:371)
		at com.sourceclear.agent.EntryPointImpl.dispatchVerbOptions(EntryPointImpl.java:320)
		at com.sourceclear.agent.EntryPointImpl.apply(EntryPointImpl.java:156)
		at com.sourceclear.agent.Main.start(Main.java:96)
		at com.sourceclear.agent.Main.main(Main.java:101)
	at org.zeroturnaround.exec.InvalidExitUtil.checkExit(InvalidExitUtil.java:27)
	at org.zeroturnaround.exec.WaitForProcess.call(WaitForProcess.java:114)
	at org.zeroturnaround.exec.ProcessExecutor.waitFor(ProcessExecutor.java:1097)
	at org.zeroturnaround.exec.ProcessExecutor.execute(ProcessExecutor.java:925)
	at com.redhat.engineering.srcclr.SrcClrInvoker.execSourceClear(SrcClrInvoker.java:142)
	at com.redhat.engineering.srcclr.SCM.call(SCM.java:121)
	at com.redhat.engineering.srcclr.SCM.call(SCM.java:40)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1743)
	at picocli.CommandLine.access$900(CommandLine.java:145)
	at picocli.CommandLine$RunAll.handle(CommandLine.java:2157)
	at picocli.CommandLine$RunAll.handle(CommandLine.java:2116)
	at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1928)
	at picocli.CommandLine.parseWithHandlers(CommandLine.java:2282)
	at com.redhat.engineering.srcclr.SrcClrWrapper.invokeWrapper(SrcClrWrapper.java:130)
	at com.redhat.engineering.srcclr.SCBase.exeSC(SCBase.java:44)
	at com.redhat.engineering.srcclr.internal.SourceClearInvokerTest.runScmGoScan(SourceClearInvokerTest.java:227)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.contrib.java.lang.system.internal.LogPrintStream$1$1.evaluate(LogPrintStream.java:30)
	at org.junit.contrib.java.lang.system.internal.PrintStreamHandler$3.evaluate(PrintStreamHandler.java:48)
	at org.junit.contrib.java.lang.system.internal.LogPrintStream$1.evaluate(LogPrintStream.java:26)
	at org.junit.contrib.java.lang.system.internal.LogPrintStream$1$1.evaluate(LogPrintStream.java:30)
	at org.junit.contrib.java.lang.system.internal.PrintStreamHandler$3.evaluate(PrintStreamHandler.java:48)
	at org.junit.contrib.java.lang.system.internal.LogPrintStream$1.evaluate(LogPrintStream.java:26)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
[DEBUG] Caught an internal exception
picocli.CommandLine$ExecutionException: Error while calling command (scanning https://github.com/srcclr/example-go-glide version 96b1262): com.redhat.engineering.srcclr.utils.InternalException: Error executing SourceClear
	at picocli.CommandLine.executeUserObject(CommandLine.java:1752)
	at picocli.CommandLine.access$900(CommandLine.java:145)
	at picocli.CommandLine$RunAll.handle(CommandLine.java:2157)
	at picocli.CommandLine$RunAll.handle(CommandLine.java:2116)
	at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1928)
	at picocli.CommandLine.parseWithHandlers(CommandLine.java:2282)
	at com.redhat.engineering.srcclr.SrcClrWrapper.invokeWrapper(SrcClrWrapper.java:130)
	at com.redhat.engineering.srcclr.SCBase.exeSC(SCBase.java:44)
	at com.redhat.engineering.srcclr.internal.SourceClearInvokerTest.runScmGoScan(SourceClearInvokerTest.java:227)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.contrib.java.lang.system.internal.LogPrintStream$1$1.evaluate(LogPrintStream.java:30)
	at org.junit.contrib.java.lang.system.internal.PrintStreamHandler$3.evaluate(PrintStreamHandler.java:48)
	at org.junit.contrib.java.lang.system.internal.LogPrintStream$1.evaluate(LogPrintStream.java:26)
	at org.junit.contrib.java.lang.system.internal.LogPrintStream$1$1.evaluate(LogPrintStream.java:30)
	at org.junit.contrib.java.lang.system.internal.PrintStreamHandler$3.evaluate(PrintStreamHandler.java:48)
	at org.junit.contrib.java.lang.system.internal.LogPrintStream$1.evaluate(LogPrintStream.java:26)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
Caused by: com.redhat.engineering.srcclr.utils.InternalException: Error executing SourceClear
	at com.redhat.engineering.srcclr.SrcClrInvoker.execSourceClear(SrcClrInvoker.java:174)
	at com.redhat.engineering.srcclr.SCM.call(SCM.java:121)
	at com.redhat.engineering.srcclr.SCM.call(SCM.java:40)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1743)
	... 43 common frames omitted
Caused by: org.zeroturnaround.exec.InvalidExitValueException: Unexpected exit value: 1, allowed exit values: [0], executed command [/usr/local/Cellar/srcclr/3.4.17/libexec/jre/bin/java, -jar, /usr/local/Cellar/srcclr/3.4.17/libexec/srcclr-3.4.17.jar, --debug, scan, --json, --skip-collectors="SOFile", --url, https://github.com/srcclr/example-go-glide, --ref, 96b1262, --no-upload] in directory /var/folders/0h/28qktgvj01j9hp61hck2p7sc0000gn/T/sourceclear-invoker-5314633448743086581 with environment {GIT_BRANCH=null, GIT_URL=null, GOPATH=/var/folders/0h/28qktgvj01j9hp61hck2p7sc0000gn/T/sourceclear-gopath-8004744084892554207}, output was 7590 bytes (truncated):
```

**Comment by rnc** [comment]
Glide needs to be installed or use `-DskipTests=true`
