### ISSUE TITLE
NoSuchElementException runing tool

### ISSUE THREAD

**Issue by tombentley** [project-ncl/sourceclear-invoker#86]
Trying to run the tool on Kafka 2.4, using `java -jar target/srcclr-1.4-jar-with-dependencies.jar --product=cpe:/a:redhat:amq_streams:1.4 --product-version=1.4 scm --url=https://github.com/apache/kafka.git --ref=2.4.0`, at the end of the scan (after the report URL is logged) I get 

```
Exception in thread "main" java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135)
	at com.redhat.engineering.srcclr.notification.DefaultStringNotifier.toString(DefaultStringNotifier.java:30)
	at com.redhat.engineering.srcclr.notification.LogFileNotifier.notify(LogFileNotifier.java:47)
	at com.redhat.engineering.srcclr.SrcClrWrapper.notifyListeners(SrcClrWrapper.java:210)
	at com.redhat.engineering.srcclr.SCM.call(SCM.java:131)
	at com.redhat.engineering.srcclr.SCM.call(SCM.java:40)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1743)
	at picocli.CommandLine.access$900(CommandLine.java:145)
	at picocli.CommandLine$RunAll.handle(CommandLine.java:2157)
	at picocli.CommandLine$RunAll.handle(CommandLine.java:2116)
	at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1928)
	at picocli.CommandLine.parseWithHandlers(CommandLine.java:2282)
	at com.redhat.engineering.srcclr.SrcClrWrapper.invokeWrapper(SrcClrWrapper.java:130)
	at com.redhat.engineering.srcclr.SrcClrWrapper.main(SrcClrWrapper.java:118)
```

**Comment by rnc** [comment]
Thanks for the report.
